### ISSUE TITLE
All the work was scheduled onto a single GPU?

### ISSUE THREAD

**Issue by ali-ramadhan** [JuliaGPU/DaggerGPU.jl#7] opened 2020-10-22 22:58 UTC
Not sure if this is a bug but running the script below works (:tada:) but all the work was scheduled onto a single GPU. I guess I was expecting it to distribute the work equally among the 3 idle GPUs.

![2020-10-22 18_55_01-Manjaro Architect (KDE)  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/20099589/96938476-83938600-1498-11eb-9398-0148f5828889.png)

```julia
using Distributed

n_procs = 16
procs = Distributed.addprocs(n_procs)

@everywhere begin
    using CUDA
    using Dagger
    using DaggerGPU
    using Oceananigans
end

@everywhere function vast_empty_ocean(arch, N, Nt, Δt)
    @info "Worker $(myid()) is spinning up..."
    grid = RegularCartesianGrid(size=(N, N, N), extent=(1, 1, 1))
    model = IncompressibleModel(architecture=arch, grid=grid)
    [time_step!(model, Δt) for _ in 1:Nt]
    return model.clock.time
end

cuproc = DaggerGPU.processor(:CUDA)
opts = Dagger.Sch.ThunkOptions(;proctypes=[cuproc])

ctx = Dagger.Context()
# addprocs!(ctx, procs)
thunk = Dagger.delayed(vcat, options=opts)((Dagger.delayed(vast_empty_ocean, options=opts)(GPU(), 32, 1000, n) for n in 1:n_procs)...)
job = @async collect(ctx, thunk)
@time result = fetch(job)

Distributed.workers() |> Distributed.rmprocs
```

**Comment by jpsamaroo** [comment] 2020-10-23 00:33
Good catch! The issue is that at https://github.com/JuliaGPU/DaggerGPU.jl/blob/a33068b4c0edfc4cf2b6cd8ca864f5e2a782c1cf/src/cu.jl#L24 and https://github.com/JuliaGPU/DaggerGPU.jl/blob/a33068b4c0edfc4cf2b6cd8ca864f5e2a782c1cf/src/cu.jl#L46, we don't actually switch context or device. They're commented out because I ran into CUDA `ILLEGAL_ACCESS` errors (or something like that) while developing DaggerGPU.

If you happen to know how to properly do this, I'd be happy to fix this so it properly uses multiple GPUs. We may also need to add a `Dagger.move` dispatch that does a CUDA DtoD transfer to ensure Dagger automatically moves data to the right device.

**Comment by ali-ramadhan** [comment] 2020-10-23 09:53
Ah I usually use [`device!`](https://juliagpu.gitlab.io/CUDA.jl/api/essentials/#CUDA.device!-Tuple{CuDevice}) to change which GPU I'm running on manually.

I usually pass in the integer ID of the GPU but maybe if `proc.ctx` is a `CuContext` then `device!(f::Function, dev::CuDevice)` could be used? Couldn't figure out how to convert a `CuContext` to the appropriate `CuDevice` though. @vchuravy would probably know (and maybe what I'm saying doesn't make sense...)

**Comment by jpsamaroo** [comment] 2023-06-16 21:57
This appears to be fixed on `master`

**Closed** 2023-06-16 21:57 UTC
